spring:
  security:
    user:
      name: admin
      password: secret
      roles:
        - ADMIN

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'

logging:
  level:
    org.springframework.security: debug

debug: true
